name: PR Validation 
on: 
  pull_request:
    # types: ["opened"]
    branches: 
      - dev

jobs:
    validate:
      runs-on: ubuntu-latest
      steps:
        - name: Setup Code
          uses: "actions/checkout@v4" 
        - name: Setup Pnpm
          uses: "pnpm/setup@v1"
          with:
            version: 10
            cache: true
        - name: Install Dependencies 
          run: "pnpm install"
        - name: Build Application
          run: "pnpm run build"